id: A096D218D
title: Offering Prayer to Changshönma, Protectress Riding upon a Wolf
type: translation
pechas:
- IE57EAD54
- IADAF94FB
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:58:17.094510
  last_modified_at: 2023-01-04 12:58:17.094529
  collections:
  - Lodi Gyari Rinpoche
  - Works of Tibetan Masters
alignment_to_base:
  IE57EAD54/FD81: 833E
  IADAF94FB/A47E: 833E
